# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
