# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160618_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='videos',
            field=models.ManyToManyField(blank=True, to='videos.Video'),
        ),
    ]
