# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20160618_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='\nCheck out this awesome video.\n'),
        ),
    ]
