# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_video_share_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='share_message',
            field=models.TextField(default='Check out this awesome video. '),
        ),
    ]
